name: Dev Java Maven Build
run-name: Action Maven Java Build - ${{ github.repository }}

on:
  push:
    branches: [ test ]

jobs:
  dev-java17-build-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
          cache: maven
      - name: Configure Maven settings.xml
        run: |
          echo '<settings>
                  <servers>
                    <server>
                      <id>github-core</id>
                      <username>${{ github.actor }}</username>
                      <password>${{ secrets.GH_PACKAGES_TOKEN }}</password>
                    </server>
                    <server>
                      <id>github-db</id>
                      <username>${{ github.actor }}</username>
                      <password>${{ secrets.GH_PACKAGES_TOKEN }}</password>
                    </server>
                    <server>
                      <id>github</id>
                      <username>${{ github.actor }}</username>
                      <password>${{ secrets.GH_PACKAGES_TOKEN }}</password>
                    </server>
                  </servers>
                </settings>' > $HOME/.m2/settings.xml
      - name: Build with Maven
        run: mvn clean deploy -DskipTests